### ISSUE TITLE
Align repository with other sitefinity package

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Core#1]
When you have time, please update this repository's settings, readme, etc... to be on par with the other sitefinity repository https://github.com/AndcultureCode/AndcultureCode.CSharp.Sitefinity.Testing

- [ ] README (overall markdown structure, badges)
- [ ] Repo description
- [ ] Repo tags

**Comment by Stefanie899** [comment]
I believe this was resolved with the merge of version 1 of this package.
