### ISSUE TITLE
Can we delete this repository?

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Core#2]
Is this repository a candidate for deletion? Doesn't appear to be used.

**Comment by Stefanie899** [comment]
@wintondeshong This was created a little prematurely, but there is code that needs to be moved into this repository, Hopefully sooner rather than later.

**Comment by wintondeshong** [comment]
Alright, I'll leave it and assign permissions 👍
