### ISSUE TITLE
Enhance MapTo extension method to handle mapping enums from strings

### ISSUE THREAD

**Issue by cspath1** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Core#36]
When Sitefinity maps values represented by enums into the database, they are stored as strings and pulled back out and mapped to Sitefinity's `DynamicContent` object as a string. This leads to data not being properly mapped from their `DynamicContent` model to our internal models when using the `MapTo` method.

**Comment by KevinBusch** [comment]
Addressed with issues #37 and release v1.1.1
