### ISSUE TITLE
Add IncludeBase, Include, and IncludeExtensions to simplify generating Include paths

### ISSUE THREAD

**Issue by Stefanie899** [AndcultureCode/AndcultureCode.CSharp.Sitefinity.Core#4]
in `DynamicContentExtensions.cs`, the `MapTo<T>` function has an optional `includes` parameter. This is a string with multiple include paths, separated by commas, e.g. `Product.Orders,Category.ParentCategory`.

In order to simplify building these include paths, we should add our helper classes to this repository -- namely `IncludeBase.cs`, `Include.cs`, and `IncludeExtensions.cs` to more easily generate the include paths to be passed into the `MapTo<T>` function.

These classes are currently contained only in proprietary repos, so an andculture engineer should be contacted to get directed to the existing code.

**Comment by brandongregoryscott** [comment]
@Stefanie899 If possible, it would be awesome to move this to one of the non-Sitefinity repos like Core or Extensions. I think we have an open issue for it on [Extensions](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/issues/25), and there was some initial discussion on it, but no further movement. Some misunderstandings on an EF dependency (I don't believe there is one, but we should double check). Unless there's Sitefinity-specific behavior, it would be nice to have this functionality for all our projects, too.

**Comment by Stefanie899** [comment]
@brandongregoryscott Good call, I think it makes sense to just live in the `CSharp.Core` repo. There is no dependency on EF or Sitefinity specific logic -- I built the Sitefinity code around what already existed.

I'll close this issue and move the currently open issue in Extensions to https://github.com/AndcultureCode/AndcultureCode.CSharp.Core
